name: TIStudent
description: Thapar Institute Student App
version: 0.0.1+1
repository: https://github.com/ShivamGoyal1899/TIStudent
author: Shivam Goyal

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.2.5
  font_awesome_flutter: ^8.5.0
  path_provider: ^1.4.0
  screenshot_and_share: ^0.0.2
  http: ^0.12.0
  permission_handler: ^4.0.0
  flutter_html: ^0.10.4
  firebase_auth: ^0.14.0+2
  google_sign_in: ^4.0.6
  cloud_firestore: ^0.12.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 900